name: Check Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:

      - name: Archref Repository
        uses: actions/checkout@v2

      - name: Setup Node  ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: npm install, Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Audit
        run: yarn  audit

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

